### ISSUE TITLE
Question about `selenium-server` command

### ISSUE THREAD

**Issue by carter-page** [yale-cpsc-213/social-todo-selenium-tests#1]
@kljensen, is the command `selenium-server` that you type an alias for `java -jar selenium-server-standalone-3.3.1.jar`? I am struggling to follow along with your instructions on how to setup the environment for testing...

![2017-04-13 10 33 40](https://cloud.githubusercontent.com/assets/21993426/25009456/ba69b4a8-2034-11e7-85ee-0795fc7ebe3d.gif)

**Comment by kljensen** [comment]
Carter - the command I used in the video is `selenium-server`, and that is
just a shell script with the following content

```
#!/bin/bash
exec java  -jar
/usr/local/Cellar/selenium-server-standalone/3.0.1/libexec/selenium-server-standalone-3.0.1.jar
"$@"
```

**Comment by carter-page** [comment]
Aha! It was hiding in your cellar. 🍺 `brew install selenium-server-standalone` is 10x easier than dealing with the Selenium downloads page. Thank you!

http://stackoverflow.com/a/28640644/6819862
